apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpfman
  namespace: kube-system
  labels:
    app: bpfman
spec:
  selector:
    matchLabels:
      app: bpfman
  template:
    metadata:
      labels:
        app: bpfman
    spec:
      containers:
        - name: bpfman
          image: bpfman:dev
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: bpffs
              mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
      volumes:
        - name: bpffs
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
      tolerations:
        - operator: Exists
